#Trabalho final CI nivel 01 -  Disparar o Pieline de testes de forma manual a  partir de um clique

# This is a basic workflow that is manually triggered

name: 'TF Execucao Manual'

#triggers gatilhos de ecxec
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependencias
        run: npm install

      - name: Execucao dos testes com cypress (end-to-end)
        run: npx cypress run

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports
